export const PRODUCTS = [
 {
 title: "Servana",
 subtitle: "Enterprise AI Orchestration",
 desc: "AI-powered SaaS platform for enterprise workflow automation and team orchestration.",
 year: "2025",
 tags: ["AI", "React", "Node.js", "PostgreSQL"],
 gradient: "linear-gradient(135deg, #c9662f 0%, #FF8F5C 100%)",
 link: "#contact",
 },
 {
 title: "Stitched Health",
 subtitle: "Intelligent Care Platform",
 desc: "HealthTech platform connecting patients with care providers through intelligent matching.",
 year: "2025",
 tags: ["HealthTech", "Python", "AWS", "React"],
 gradient: "linear-gradient(135deg, #00D4FF 0%, #0077B6 100%)",
 link: "#contact",
 },
 {
 title: "Dronetjek",
 subtitle: "Fleet Intelligence",
 desc: "End-to-end drone fleet management system with real-time telemetry and route optimization.",
 year: "2026",
 tags: ["Logistics", "IoT", "Kubernetes", "Go"],
 gradient: "linear-gradient(135deg, #7C3AED 0%, #A78BFA 100%)",
 link: "#contact",
 },
 {
 title: "Scoutify",
 subtitle: "ML-Powered Talent Matching",
 desc: "Talent scouting platform using ML to identify and match engineering candidates at scale.",
 year: "2025",
 tags: ["ML", "TypeScript", "GraphQL", "Redis"],
 gradient: "linear-gradient(135deg, #c9662f 0%, #FFB347 100%)",
 link: "#contact",
 },
 {
 title: "ExecMind",
 subtitle: "Decision Intelligence Dashboard",
 desc: "Executive decision-intelligence dashboard synthesizing real-time business signals.",
 year: "2026",
 tags: ["Data Eng", "Python", "TensorFlow", "Docker"],
 gradient: "linear-gradient(135deg, #00D4FF 0%, #48CAE4 100%)",
 link: "#contact",
 },
 {
 title: "E-Commerce Platform",
 subtitle: "High-Throughput Marketplace",
 desc: "High-throughput marketplace with real-time inventory, payments, and logistics orchestration.",
 year: "2025",
 tags: ["E-Commerce", "Next.js", "PostgreSQL", "AWS"],
 gradient: "linear-gradient(135deg, #7C3AED 0%, #C084FC 100%)",
 link: "#contact",
 },
];
